### PR TITLE
feat(ios): return asset id on ios

### PR DESCRIPTION
**Pull request by helenaford**
Thanks for submitting a PR! Please read these instructions carefully:

- [ ] Explain the **motivation** for making this change.
- [ ] Provide a **test plan** demonstrating that the code is solid.
- [ ] Match the **code formatting** of the rest of the codebase.
- [ ] Target the `master` branch, NOT a "stable" branch.

## Motivation (required)

What existing problem does the pull request solve?

## Test Plan (required)

A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  

If you have added code that should be tested, add tests.

[1]: https://medium.com/@martinkonicek/what-is-a-test-plan-8bfc840ec171#.y9lcuqqi9

### CODE REVIEW

**Comment by lukebrandonfarrell** [comment]
Oh my bad! I was a little confused as code contains both a refactor (which I think is great!) and adding the ID to response. **So ignore my last comment about using the ID for search.**. So next steps I'd say would be:

- Let's separate the refactor out into a separate PR ? (I support this change and using the function fetchPHAsset but I think we should keep any refactoring code separate from this so we can get it merged into the main repository faster, then we can PR the clean-up separately)
- Let's include the Android part
- Let us decide a new name for `includeExif` and I can make the change to update that

Let me know if you think this makes sense

**Comment by helenaford** [comment]
@lukebrandonfarrell OK great, thank you. That makes sense to merge them separately! 

I don't mind who merges it 😎 Early next week sounds awesome. Happy to do it if it's next week as I'm away this week. Just let me know 😄 

No problem, thank you for yours! 🙌

**Comment by lukebrandonfarrell** [comment]
Great @helenaford, I've pushed the updates Johan requested to https://github.com/react-native-image-picker/react-native-image-picker/pull/1795 then I'll come back and do a final CR on this, thanks!

**Comment by jimfoambox** [comment]
Hi guys, thanks for such a great library and all the awesome work you do :)

Is there any chance including the asset id on the image returned after taking a photo with launchCamera could be added in a future update?  I noticed that and the timestamp are not included, even with includeExtra set to true, in IOS only (on Android I am getting both of those when taking a photo).

**Pull request closed without merging**
